### PR TITLE
feat: support bool expr macro

### PR DESCRIPTION
**Pull request by johntaiko**
resolve https://github.com/taikoxyz/zkevm-circuits/issues/53

### CODE REVIEW

**Comment by Brechtpd** [comment]
Nice! Let's use this as the base to build more stuff upon and improve the "dsl".

I'm not going to pull this in the MPT branch just yet because I want to finish that branch up as soon as possible and not make merging it into the PSE more difficult by also including procedural macro's that currently "only" for boolean logic.

**Comment by johntaiko** [comment]
Yeah, as you said yesterday, we may still need some symbols to distinguish between DSL and Rust code. Therefore, I think DSL will be a long-term goal, including definition and implementation. 

May I commit the expr-macros to our taikoxyz/zkevm-circuits?

**Comment by Brechtpd** [comment]
Yeah sure thing!

**Comment by johntaiko** [comment]
new pr: https://github.com/taikoxyz/zkevm-circuits/pull/74

**Pull request closed without merging**
